# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Paul Jarymowycz
tagline:             'A GIS Professional and Photography Enthusiast in Brooklyn, NY'
description:         'I am a GIS professional and photography enthusiast with a background in IT, Teaching, and Environmental and Mechanical Engineering.'
url:                 https://pjarymowycz.github.io
baseurl:             https://pjarymowycz.github.io/
paginate:            5

# About/contact
author:
  name:              Paul Jarymowycz
  url:               https://twitter.com/jarymowycz
  email:             pjarymowycz@gmail.com
  github:            pjarymowycz
  linkedin:          pjarymowycz
  twitter:           jarymowycz

# Custom vars
version:             1.0.1
