# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Paul Jarymowycz
tagline:             'An Engineer and GIS Professional in Brooklyn, NY'
description:         'I am a GIS Professional and mapping enthusiast with a background in IT, Teaching, and Environmental and Mechanical Engineering.'
url:                 https://pjarymowycz.github.io/
baseurl:             https://pjarymowycz.github.io/
paginate:            5

# About/contact
author:
  name:              Paul Jarymowycz
  url:               https://twitter.com/jarymowycz
  email:             pjarymowycz@gmail.com

# Custom vars
version:             1.0.1
